/**
 * scripts/audit/classify.js
 * Read-only URL/path classifier shared by the audit reports. Maps a repo-relative
 * HTML file path to a fine-grained page category and a coarse group, based on
 * observed, current output patterns from scripts/generate-programmatic-pages.js
 * and the other active generators (see audit/build-pipeline.json for the
 * generator-to-output map this was derived from).
 *
 * Rule order matters: first match wins. Keep more specific patterns above
 * more general ones (e.g. "name x country pair" compare pages before the
 * generic "compare hub" rule).
 */

const RULES = [
  { category: 'template-source', group: 'template', test: (p) => /^templates\/[^/]+\.html$/.test(p) },
  { category: 'homepage', group: 'static', test: (p) => p === 'index.html' },
  { category: 'root-hub-page', group: 'hub', test: (p) => /^(all-name-pages|alphabet-name-pages|boy-name-pages|country-name-pages|girl-name-pages|name-pages|last-name-pages|style-name-pages)\.html$/.test(p) },

  { category: 'name-detail-page', group: 'name', test: (p) => /^name\/[^/]+\/index\.html$/.test(p) },
  { category: 'names-like-page', group: 'names-like', test: (p) => /^names-like\/[^/]+\/index\.html$/.test(p) },

  { category: 'sibling-harmony-page', group: 'sibling', test: (p) => /^names\/[^/]+\/siblings\/index\.html$/.test(p) },
  { category: 'names-hub', group: 'hub', test: (p) => p === 'names/index.html' },
  { category: 'names-letter-page', group: 'letter', test: (p) => /^names\/[a-z]\.html$/.test(p) },
  { category: 'names-letters-hub', group: 'hub', test: (p) => p === 'names/letters.html' },
  { category: 'names-gender-country-page', group: 'country', test: (p) => /^names\/(boy|girl|unisex)\/[^/]+\.html$/.test(p) },
  { category: 'names-gender-page', group: 'gender', test: (p) => /^names\/(boy|girl|unisex)\.html$/.test(p) },
  { category: 'names-country-page', group: 'country', test: (p) => /^names\/(usa|canada|france|india|ireland)\.html$/.test(p) },
  { category: 'names-style-page', group: 'style', test: (p) => /^names\/style\/[^/]+\.html$/.test(p) },
  { category: 'names-style-hub', group: 'hub', test: (p) => p === 'names/style.html' },
  { category: 'names-curated-list-page', group: 'utility', test: (p) => /^names\/(popular|trending)\.html$/.test(p) },
  { category: 'names-lastname-filter-page', group: 'surname', test: (p) => /^names\/with-last-name-[^/]+\.html$/.test(p) },
  { category: 'names-lastname-hub', group: 'hub', test: (p) => p === 'names/with-last-name.html' },

  { category: 'surname-compatibility-page', group: 'surname', test: (p) => /^baby-names-with-[^/]+\/index\.html$/.test(p) },

  { category: 'compare-name-country-pair-page', group: 'pair', test: (p) => /^compare\/[^/]+\/[^/]+-vs-[^/]+\/index\.html$/.test(p) },
  { category: 'compare-country-pair-hub', group: 'pair', test: (p) => /^compare\/[^/]+-vs-[^/]+\/index\.html$/.test(p) },
  { category: 'compare-hub', group: 'hub', test: (p) => p === 'compare/index.html' },

  { category: 'equivalents-page', group: 'equivalents', test: (p) => /^equivalents\/[^/]+\/index\.html$/.test(p) },

  { category: 'compatibility-tool-page', group: 'utility', test: (p) => p === 'compatibility/index.html' },

  { category: 'popularity-year-page', group: 'popularity', test: (p) => /^popularity\/\d{4}\.html$/.test(p) },
  { category: 'popularity-hub', group: 'hub', test: (p) => p === 'popularity/index.html' },

  { category: 'trend-page', group: 'trend', test: (p) => /^trends\/[^/]+\/index\.html$/.test(p) },
  { category: 'trends-hub', group: 'hub', test: (p) => p === 'trends/index.html' },

  { category: 'tool-landing-page', group: 'utility', test: (p) => /^tools\/[^/]+\/index\.html$/.test(p) },

  { category: 'legal-page', group: 'static', test: (p) => /^legal\/[^/]+\.html$/.test(p) },
  { category: 'about-page', group: 'static', test: (p) => p === 'about/index.html' },

  { category: 'html-sitemap', group: 'utility', test: (p) => p === 'sitemap/index.html' },
];

const CATEGORY_LABELS = {
  'homepage': 'Homepage',
  'root-hub-page': 'Root hub page (8 pages generated by generate-programmatic-pages.js)',
  'name-detail-page': 'Name detail page (meaning/origin/popularity)',
  'names-like-page': '"Names Like X" alternative-names page',
  'sibling-harmony-page': 'Sibling Harmony compatibility page',
  'names-hub': 'Names section hub',
  'names-letter-page': 'Names by letter (A–Z) page',
  'names-letters-hub': 'Letters hub',
  'names-gender-country-page': 'Names by gender + country page',
  'names-gender-page': 'Names by gender (boy/girl/unisex) page',
  'names-country-page': 'Names by country page',
  'names-style-page': 'Names by style page',
  'names-style-hub': 'Styles hub',
  'names-curated-list-page': 'Curated list page (popular/trending)',
  'names-lastname-filter-page': 'Names-with-surname filter page (/names/with-last-name-*)',
  'names-lastname-hub': 'Last-name-fit hub',
  'surname-compatibility-page': 'Surname compatibility landing page (/baby-names-with-*)',
  'compare-name-country-pair-page': 'Name × country-pair comparison page',
  'compare-country-pair-hub': 'Country-pair comparison hub',
  'compare-hub': 'Compare section hub',
  'equivalents-page': 'Cross-linguistic equivalent-name page',
  'compatibility-tool-page': 'Compatibility tool page',
  'popularity-year-page': 'Popularity-by-year page',
  'popularity-hub': 'Popularity section hub',
  'trend-page': 'Trend analysis page',
  'trends-hub': 'Trends section hub',
  'tool-landing-page': 'Tool landing page',
  'legal-page': 'Legal page (privacy/terms)',
  'about-page': 'About page',
  'html-sitemap': 'HTML sitemap',
  'template-source': 'Template source file (not a generated page)',
  'other-static': 'Other/unclassified static HTML',
};

const GROUP_LABELS = {
  name: 'Name pages',
  'names-like': 'Names Like pages',
  surname: 'Surname pages',
  country: 'Country pages',
  pair: 'Pair pages (comparisons)',
  hub: 'Hub pages',
  static: 'Static pages',
  utility: 'Utility pages',
  sibling: 'Sibling Harmony pages',
  letter: 'Letter (A–Z) pages',
  gender: 'Gender filter pages',
  style: 'Style pages',
  equivalents: 'Equivalent-name pages',
  popularity: 'Popularity pages',
  trend: 'Trend pages',
  template: 'Template sources (excluded from live page count)',
  other: 'Other/unclassified',
};

function classify(relPath) {
  for (const rule of RULES) {
    if (rule.test(relPath)) return { category: rule.category, group: rule.group };
  }
  return { category: 'other-static', group: 'other' };
}

module.exports = { classify, CATEGORY_LABELS, GROUP_LABELS, RULES };
